"""Update User and Car models to use UUID

Revision ID: 29c3d3503714
Revises: 43c3b645c626
Create Date: 2024-08-07 13:41:37.836626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '29c3d3503714'
down_revision = '43c3b645c626'
branch_labels = None
depends_on = None



def upgrade():
    op.add_column('user', sa.Column('new_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute("UPDATE \"user\" SET new_id = uuid_generate_v4()")
    op.alter_column('user', 'new_id', nullable=False)
    op.drop_constraint('user_pkey', 'user', type_='primary')
    op.create_primary_key('user_pkey', 'user', ['new_id'])
    op.drop_column('user', 'id')
    op.alter_column('user', 'new_id', new_column_name='id')
    op.alter_column('car', 'user_id', type_=postgresql.UUID(as_uuid=True), postgresql_using='user_id::uuid')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

  


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
